AWSTemplateFormatVersion: '2010-09-09'

Description: >
  AWS CloudFormation template for deploying the Operations Client Discovery Service.

Parameters:
    ArtifactBucketKey:
      Description: The key which is the path to the .zip file that contains the deployment package
      Type: String
    ArtifactBucketName:
      Description: The name of the Amazon S3 bucket where the .zip file that contains the deployment package is stored
      Type: String
    DeploymentSubdomainName:
      Description: The name of the stack containing the Subdomain output
      Type: String
    DiscoverySubdomain:
      Description: The subdomain under which the discovery service will be hosted
      Type: String
    HostedZoneId:
      Description: The HostedZone ID for the DeploymentSubdomainName
      Type: String

Resources:

  LuloCustomResourcesLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref ArtifactBucketName
        S3Key: !Ref ArtifactBucketKey
      Description: The lambda containing our custom lulo plugins for Operations Discovery Service
      Handler: index.handler
      Role: !GetAtt LuloCustomResourcesLambdaFunctionExecutionRole.Arn
      Runtime: nodejs8.10

  SubdomainCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    DependsOn: LuloCustomResourcesLambdaFunction
    Properties:
      DomainName: !Join
        - '.'
        - - !Ref DiscoverySubdomain
          - !Ref DeploymentSubdomainName

  DiscoveryApiDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      RegionalCertificateArn:
        !Ref SubdomainCertificate
      DomainName: !Join
        - '.'
        - - !Ref DiscoverySubdomain
          - !Ref DeploymentSubdomainName
      EndpointConfiguration:
        Types:
          - REGIONAL

  LuloCustomResourcesLambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-LuloCustomResourcesLambdaFunctionPolicy'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - route53:ChangeResourceRecordSets
                  - apigateway:*
                  - logs:*
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  OperationsClientCustomDomain:
    Type: Custom::Route53RecordSetAPIGatewayRegionalDomain
    DependsOn: DiscoveryApiDomain
    Properties:
      ServiceToken: !GetAtt LuloCustomResourcesLambdaFunction.Arn
      HostedZoneId:
        !Ref HostedZoneId
      DomainName:  !Join
        - '.'
        - - !Ref DiscoverySubdomain
          - !Ref DeploymentSubdomainName

Outputs:
    OperationsDiscoveryEndpointUri:
        Value: !Join
          - '.'
          - - !Ref DiscoverySubdomain
            - !Ref DeploymentSubdomainName

        Description: 'The location of the operations discovery endpoint that was created'
        Export:
            Name: !Sub '${AWS::StackName}-OperationsDiscoveryEndpointUri'
